[build]
  command = "pnpm install && pnpm run build"
  publish = "dist/public"

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
